services:
  open-webui:
    container_name: open-webui
    labels:
      net.unraid.docker.icon: https://raw.githubusercontent.com/selfhst/icons/main/svg/open-webui.svg
    image: ghcr.io/open-webui/open-webui:${OPENWEBUI_VERSION}
    mem_limit: ${OPENWEBUI_MEMORY:-5g}
    restart: ${OPENWEBUI_RESTART:-unless-stopped}
    environment:
      TZ: ${TZ:-America/Chicago}
      ENABLE_PERSISTENT_CONFIG: "false"
      ENABLE_OLLAMA_API: "false"
      OPENAI_API_BASE_URL: ${OPENAI_API_BASE_URL:-http://llamacpp:8080/v1}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    volumes:
      - "${CONTAINER_DATA}/open-webui:/app/backend/data:rw"

  searxng-ai:
    container_name: searxng-ai
    labels:
      net.unraid.docker.icon: https://raw.githubusercontent.com/selfhst/icons/main/svg/searxng.svg
    image: searxng/searxng:${SEARXNG_VERSION}
    restart: ${SEARXNG_RESTART:-unless-stopped}
    environment:
      TZ: ${TZ:-America/Chicago}
      INSTANCE_NAME: ${INSTANCE_NAME:-}
      SEARXNG_LIMITER: "false"
      SEARXNG_PUBLIC_INSTANCE: "false"
      SEARXNG_BIND_ADDRESS: "0.0.0.0"
    volumes:
      - "${CONTAINER_DATA}/searxng-ai:/etc/searxng:rw"
    tmpfs:
      - "/var/cache/searxng"

  tika:
    container_name: tika
    labels:
      net.unraid.docker.icon: https://raw.githubusercontent.com/selfhst/icons/main/svg/apache-tika.svg
    image: docker.io/apache/tika:${TIKA_VERSION}
    restart: ${TIKA_RESTART:-unless-stopped}
    environment:
      TZ: ${TZ:-America/Chicago}
