services:
  komodo-periphery:
    container_name: komodo-periphery
    image: ghcr.io/moghtech/komodo-periphery:${COMPOSE_KOMODO_IMAGE_TAG:-2}
    init: true
    restart: unless-stopped
    labels:
      komodo.skip: # Prevent Komodo from stopping with StopAllContainers
    security_opt:
      - label:disable
    ports:
      - "${KOMODO_PERIPHERY_PORT:-8120}:8120"
    volumes:
      - ${CONTAINER_DATA}/komodo-periphery/keys:/config/keys
      - ${KOMODO_PERIPHERY_PATH}:${KOMODO_PERIPHERY_PATH}
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc:/proc
    environment:
      PERIPHERY_SSL_ENABLED: ${PERIPHERY_SSL_ENABLED:-true}
      PERIPHERY_PASSKEYS: ${KOMODO_PASSKEY}
      PERIPHERY_ROOT_DIRECTORY: ${KOMODO_PERIPHERY_PATH}
      PERIPHERY_CORE_ADDRESS: ${PERIPHERY_CORE_ADDRESS}
      PERIPHERY_CONNECT_AS: ${PERIPHERY_CONNECT_AS}
      PERIPHERY_ONBOARDING_KEY: ${PERIPHERY_ONBOARDING_KEY}
