services:
  tdarr_node:
    container_name: tdarr_node
    labels:
      net.unraid.docker.icon: https://raw.githubusercontent.com/selfhst/icons/main/png/tdarr.png
    image: ghcr.io/haveagitgat/tdarr_node:${TDARR_NODE_VERSION}
    restart: ${TDARR_RESTART:-unless-stopped}
    cpus: ${TDARR_NODE_CPUS:-4}
    mem_limit: ${TDARR_NODE_MEM_LIMIT:-8g}
    depends_on:
      - tdarr
    devices:
      - "/dev/dri/renderD129:/dev/dri/renderD129"
    environment:
      TZ: ${TZ:-America/Chicago}
      HOST_CONTAINERNAME: ${HOST_CONTAINERNAME:-tdarr_node}
      serverIP: ${SERVER_IP:-192.168.10.20}
      serverPort: ${SERVER_PORT:-8266}
      nodeIP: ${TDARR_NODE_NODE_IP:-192.168.10.20}
      nodeID: ${TDARR_NOTE_NODE_ID:-Arc Pro B70}
      PUID: ${PUID:-99}
      PGID: ${PGID:-100}
    ports:
      - "${TDARR_NODE_PORT_8267:-8267}:8267"
