services:
  # paperless-ngx main service
  paperless:
    image: ghcr.io/paperless-ngx/paperless-ngx:${PAPERLESS_VERSION:-latest}
    container_name: paperless-ngx
    restart: unless-stopped
    env_file: 
      - ./paperless/.env
    depends_on:
      - postgres
      - redis
      - gotenberg
      - tika
    # ports:
    #   - "8000:8000"
    volumes:
      - ${CONTAINER_DATA}/paperless/paperless/data:/usr/src/paperless/data
      - ${CONTAINER_DATA}/paperless/paperless/media:/usr/src/paperless/media
      - ${CONTAINER_DATA}/paperless/paperless/export:/usr/src/paperless/export
      - ${CONTAINER_DATA}/paperless/paperless/consume:/usr/src/paperless/consume
  
  # postgres database for paperless-ngx
  postgres:
    image: postgres:${POSTGRES_VERSION:-18}
    restart: unless-stopped
    container_name: paperless-postgres
    env_file: 
      - ./postgres/.env
    volumes:
      - ${CONTAINER_DATA}/paperless/postgres/data:/var/lib/postgresql
  
  # redis database for paperless-ngx
  redis:
    image: docker.io/library/redis:${REDIS_VERSION:-8}
    container_name: paperless-redis
    restart: unless-stopped
    env_file: 
      - ./redis/.env
    volumes:
      - ${CONTAINER_DATA}/paperless/redis/data:/data
  
  # gotenberg service that paperless uses for document conversion
  gotenberg:
    image: docker.io/gotenberg/gotenberg:${GOTENBERG_VERSION:-8.25}
    container_name: paperless-gotenberg
    env_file: 
      - ./gotenberg/.env
    restart: unless-stopped
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"
  
  # tika service that paperless uses for document text extraction
  tika:
    image: docker.io/apache/tika:${TIKA_VERSION:-latest}
    container_name: paperless-tika
    restart: unless-stopped
    env_file: ./tika/.env

  # paperless-ai service
  paperless-ai:
    image: clusterzx/paperless-ai:${PAPERLESS_AI_VERSION:-latest}
    container_name: paperless-ai
    restart: unless-stopped
    depends_on:
      - paperless
    # ports:
    #   - "3000:3000"
    env_file:
      - ./paperless-ai/.env
    volumes:
      - ${CONTAINER_DATA}/paperless/paperless-ai/data:/app/data

  # paperless-gpt service
  paperless-gpt:
    image: icereed/paperless-gpt:${PAPERLESS_GPT_VERSION:-latest}
    container_name: paperless-gpt
    restart: unless-stopped
    depends_on:
      - paperless
    # ports:
    #   - "3002:8080"
    env_file:
      - ./paperless-gpt/.env
    volumes:
      - ${CONTAINER_DATA}/paperless/paperless-gpt/prompts:/app/prompts
