services:
  paperless:
    labels:
      net.unraid.docker.icon: https://raw.githubusercontent.com/selfhst/icons/main/svg/paperless-ngx.svg
  postgres:
    labels:
      net.unraid.docker.icon: https://raw.githubusercontent.com/selfhst/icons/main/svg/postgresql.svg
  redis:
    labels:
      net.unraid.docker.icon: https://raw.githubusercontent.com/selfhst/icons/main/svg/redis.svg
  paperless-ai:
    labels:
      net.unraid.docker.icon: https://raw.githubusercontent.com/selfhst/icons/main/png/paperless-ai.png
