services:
  authentik-postgresql:
    labels:
      net.unraid.docker.icon: https://raw.githubusercontent.com/selfhst/icons/main/svg/postgresql.svg
  authentik-redis:
    labels:
      net.unraid.docker.icon: https://raw.githubusercontent.com/selfhst/icons/main/svg/redis.svg
  authentik:
    labels:
      net.unraid.docker.icon: https://raw.githubusercontent.com/selfhst/icons/main/svg/authentik.svg
  authentik-worker:
    labels:
      net.unraid.docker.icon: https://raw.githubusercontent.com/selfhst/icons/main/svg/authentik.svg
