services:
  quay-clair-postgresql:
    networks:
      - backend

  quay-clair:
    networks:
      - backend

  quay-mirror:
    networks:
      - frontend
      - backend

  quay-postgresql:
    networks:
      - backend

  quay-redis:
    networks:
      - backend

  quay:
    networks:
      - frontend
      - backend

networks:
  frontend:
    external: true
  backend:
