services:
  quay-clair-postgresql:
    labels:
      net.unraid.docker.icon: https://raw.githubusercontent.com/selfhst/icons/main/svg/postgresql.svg
  quay-postgresql:
    labels:
      net.unraid.docker.icon: https://raw.githubusercontent.com/selfhst/icons/main/svg/postgresql.svg
  quay-redis:
    labels:
      net.unraid.docker.icon: https://raw.githubusercontent.com/selfhst/icons/main/svg/redis.svg
  quay:
    labels:
      net.unraid.docker.icon: https://raw.githubusercontent.com/selfhst/icons/main/svg/harbor.svg
