services:
  immich-postgresql:
    labels:
      net.unraid.docker.icon: https://raw.githubusercontent.com/selfhst/icons/main/svg/postgresql.svg
  immich:
    labels:
      net.unraid.docker.icon: https://raw.githubusercontent.com/selfhst/icons/main/svg/immich.svg
