################################
# 🦎 KOMODO COMPOSE - MONGO 🦎 #
################################

## This compose file will deploy:
##   1. MongoDB
##   2. Komodo Core
## (The core-host Periphery is managed by systemd, not this compose.)

services:
  mongo:
    image: mongo:${MONGO_VERSION}
    container_name: komodo-mongo
    labels:
      komodo.skip: # Prevent Komodo from stopping with StopAllContainers
    command: --quiet --wiredTigerCacheSizeGB 0.25
    restart: ${KOMODO_MONGO_RESTART:-unless-stopped}
    # ports:
    #   - 27017:27017
    volumes:
      - /srv/container-data/komodo/mongo-data:/data/db
      - /srv/container-data/komodo/mongo-config:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${KOMODO_DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${KOMODO_DB_PASSWORD}
  
  core:
    image: ghcr.io/moghtech/komodo-core:${COMPOSE_KOMODO_IMAGE_TAG}
    container_name: komodo-core 
    init: true
    labels:
      komodo.skip: # Prevent Komodo from stopping with StopAllContainers
    restart: ${KOMODO_CORE_RESTART:-unless-stopped}
    depends_on:
      - mongo
    ports:
      - ${KOMODO_CORE_PORT:-9120}:9120
    env_file: ./.env
    environment:
      KOMODO_DATABASE_ADDRESS: mongo:27017
      KOMODO_DATABASE_USERNAME: ${KOMODO_DB_USERNAME}
      KOMODO_DATABASE_PASSWORD: ${KOMODO_DB_PASSWORD}
    volumes:
      - ${CONTAINER_DATA:-/srv/container-data}/komodo/keys:/config/keys
      ## Store dated backups of the database - https://komo.do/docs/setup/backup
      - /srv/container-data/komodo/backups:/backups
      ## Store sync files on server
      # - /path/to/syncs:/syncs
      ## Optionally mount a custom core.config.toml
      # - /path/to/core.config.toml:/config/config.toml
