services:
  newt:
    image: fosrl/newt:${NEWT_VERSION:-latest}
    container_name: newt
    restart: ${NEWT_RESTART:-unless-stopped}
    environment:
      - PANGOLIN_ENDPOINT=${PANGOLIN_ENDPOINT}
      - NEWT_ID=${NEWT_ID}
      - NEWT_SECRET=${NEWT_SECRET}