version = 1

[*]
sleep-idle-seconds = 600
jinja = true
no-webui = true
cont-batching = true
cache-type-k = q8_0
cache-type-v = q8_0
no-mmap = true
n-gpu-layers = 99
flash-attn = true
batch-size = 2048
ubatch-size = 2048
repeat-penalty = 1.0
n-cpu-moe = 0
no-kv-offload = true

[ornith-9b]
hf-repo = bartowski/deepreinforce-ai_Ornith-1.0-9B-GGUF
hf-file = deepreinforce-ai_Ornith-1.0-9B-Q8_0.gguf
# mmproj-url = https://huggingface.co/bartowski/deepreinforce-ai_Ornith-1.0-9B-GGUF/resolve/main/mmproj-deepreinforce-ai_Ornith-1.0-9B-f16.gguf
ctx-size = 262144
temp = 0.6
top-p = 0.95

[gpt-oss]
hf-repo = unsloth/gpt-oss-20b-GGUF
hf-file = gpt-oss-20b-Q5_K_M.gguf
ctx-size = 131072

[gemma4]
hf-repo = unsloth/gemma-4-26B-A4B-it-GGUF
hf-file = gemma-4-26B-A4B-it-Q8_0.gguf
# mmproj-url = https://huggingface.co/unsloth/gemma-4-26B-A4B-it-GGUF/resolve/main/mmproj-BF16.gguf
ctx-size = 262144
spec-type = draft-mtp
spec-draft-n-max = 4
temp = 0.6
top-p = 0.95

[ornith-35b]
hf-repo = bartowski/deepreinforce-ai_Ornith-1.0-35B-GGUF
hf-file = deepreinforce-ai_Ornith-1.0-35B-Q5_K_M.gguf
# mmproj-url = https://huggingface.co/bartowski/deepreinforce-ai_Ornith-1.0-35B-GGUF/resolve/main/mmproj-deepreinforce-ai_Ornith-1.0-35B-f16.gguf
ctx-size = 262144
temp = 0.6
top-p = 0.95

[qwen3-coder]
hf-repo = unsloth/Qwen3-Coder-Next-GGUF
hf-file = Qwen3-Coder-Next-Q4_K_M.gguf
ctx-size = 262144
n-cpu-moe = 43

[qwen3-next-instruct]
hf-repo = unsloth/Qwen3-Next-80B-A3B-Instruct-GGUF
hf-file = Qwen3-Next-80B-A3B-Instruct-Q4_K_M.gguf
ctx-size = 262144
n-cpu-moe = 43

[qwen3-next-think]
hf-repo = unsloth/Qwen3-Next-80B-A3B-Thinking-GGUF
hf-file = Qwen3-Next-80B-A3B-Thinking-Q4_K_M.gguf
ctx-size = 262144
n-cpu-moe = 43

[qwen3.6]
hf-repo = unsloth/Qwen3.6-35B-A3B-GGUF
hf-file = Qwen3.6-35B-A3B-UD-Q5_K_M.gguf
# mmproj-url = https://huggingface.co/unsloth/Qwen3.6-35B-A3B-GGUF/resolve/main/mmproj-BF16.gguf
ctx-size = 262144
n-cpu-moe = 8

[glm-4.7-flash]
hf-repo = unsloth/GLM-4.7-Flash-GGUF
hf-file = GLM-4.7-Flash-Q5_K_M.gguf
ctx-size = 131072

[cydonia-24b-v4.3]
hf-repo = bartowski/TheDrummer_Cydonia-24B-v4.3-GGUF
hf-file = TheDrummer_Cydonia-24B-v4.3-Q5_K_M.gguf
ctx-size = 131072
cache-type-k = q4_0
cache-type-v = q4_0

[dans-pe-24b-v1.3.0]
hf-repo = bartowski/PocketDoc_Dans-PersonalityEngine-V1.3.0-24b-GGUF
hf-file = PocketDoc_Dans-PersonalityEngine-V1.3.0-24b-Q5_K_M.gguf
ctx-size = 131072
cache-type-k = q4_0
cache-type-v = q4_0

[qwythos-9b]
hf-repo = empero-ai/Qwythos-9B-Claude-Mythos-5-1M-GGUF
hf-file = Qwythos-9B-Claude-Mythos-5-1M-BF16.gguf
# mmproj-url = https://huggingface.co/empero-ai/Qwythos-9B-Claude-Mythos-5-1M-GGUF/resolve/main/mmproj-Qwythos-9B-Claude-Mythos-5-1M-F16.gguf
ctx-size = 1048576
