version = 1

[*]
sleep-idle-seconds = 600
jinja = true
no-webui = true
cont-batching = true
cache-type-k = q4_0
cache-type-v = q4_0
; no-mmap = true
n-gpu-layers = 99
flash-attn = true
batch-size = 2048
ubatch-size = 512
image-min-tokens = 1024
repeat-penalty = 1.0
n-cpu-moe = 0
n-slots = 1

[ornith-9b]
hf-repo = bartowski/deepreinforce-ai_Ornith-1.0-9B-GGUF
hf-file = deepreinforce-ai_Ornith-1.0-9B-Q8_0.gguf
ctx-size = 262144
temp = 0.6
top-p = 0.95

[gpt-oss]
hf-repo = unsloth/gpt-oss-20b-GGUF
hf-file = gpt-oss-20b-Q5_K_M.gguf
ctx-size = 131072
temp = 1.0
top-p = 1.0

[gemma4]
hf-repo = unsloth/gemma-4-26B-A4B-it-GGUF
hf-file = gemma-4-26B-A4B-it-Q8_0.gguf
ctx-size = 262144
n-cpu-moe = 16
spec-type = draft-mtp
spec-draft-n-max = 4
temp = 1.0
top-p = 0.95

[ornith-35b]
hf-repo = bartowski/deepreinforce-ai_Ornith-1.0-35B-GGUF
hf-file = deepreinforce-ai_Ornith-1.0-35B-Q5_K_M.gguf
ctx-size = 262144
temp = 0.6
top-p = 0.95

[qwen3-next-instruct]
hf-repo = unsloth/Qwen3-Next-80B-A3B-Instruct-GGUF
hf-file = Qwen3-Next-80B-A3B-Instruct-Q4_K_M.gguf
ctx-size = 262144
n-cpu-moe = 43
no-kv-offload = true
temp = 0.7
top-p = 0.8

[qwen3-next-think]
hf-repo = unsloth/Qwen3-Next-80B-A3B-Thinking-GGUF
hf-file = Qwen3-Next-80B-A3B-Thinking-Q4_K_M.gguf
ctx-size = 262144
n-cpu-moe = 43
no-kv-offload = true
temp = 0.6
top-p = 0.95

[qwen3.8-27b-instruct]
hf-repo = unsloth/Qwen3.8-27B-GGUF
hf-file = Qwen3.8-27B-Q5_K_M.gguf
ctx-size = 262144
temp = 0.7
top-p = 0.80
chat-template-kwargs = {"enable_thinking": false}

[qwen3.8-27b-think]
hf-repo = unsloth/Qwen3.8-27B-GGUF
hf-file = Qwen3.8-27B-Q5_K_M.gguf
ctx-size = 262144
temp = 1.0
top-p = 0.95
chat-template-kwargs = {"reasoning_effort": "medium"}
reasoning = true
reasoning-preserve = true
spec-type = draft-mtp
spec-draft-n-max = 3

[glm-4.7-flash]
hf-repo = unsloth/GLM-4.7-Flash-GGUF
hf-file = GLM-4.7-Flash-Q5_K_M.gguf
ctx-size = 131072
temp = 1.0
top-p = 0.95

[huihui-mistral-24b-rp]
hf-repo = mradermacher/Huihui-Mistral-Small-3.2-24B-Instruct-2506-abliterated-llamacppfixed-GGUF
hf-file = Huihui-Mistral-Small-3.2-24B-Instruct-2506-abliterated.Q5_K_M.gguf
ctx-size = 131072
temp = 0.3

[qwen3-embedding:8b]
hf-repo = Qwen/Qwen3-Embedding-8B-GGUF
hf-file = Qwen3-Embedding-8B-Q6_K.gguf
embedding = true
pooling = last
ctx-size = 32768
