services:
  mcphub-postgres:
    container_name: mcphub-postgres
    image: postgres:${POSTGRES_VERSION}
    restart: unless-stopped
    environment:
      POSTGRES_DB: mcphub
      POSTGRES_USER: mcphub
      POSTGRES_PASSWORD: ${MCPHUB_POSTGRES_PASSWORD}
    volumes:
      - ${CONTAINER_DATA}/mcphub/postgres:/var/lib/postgresql/data
    networks:
      - backend

  mcphub:
    image: samanhappy/mcphub:${MCPHUB_VERSION}
    container_name: mcphub
    restart: ${SVC_RESTART:-unless-stopped}
    depends_on:
      - mcphub-postgres
    environment:
      - DB_URL=postgresql://mcphub:${MCPHUB_POSTGRES_PASSWORD}@mcphub-postgres:5432/mcphub
      - BETTER_AUTH_ENABLED=true
      - BETTER_AUTH_URL=https://mcphub.mcdade.app
      - BETTER_AUTH_OIDC_ENABLED=true
      - BETTER_AUTH_OIDC_DISCOVERY_URL=https://auth.mcdade.app/application/o/mcphub/.well-known/openid-configuration
      - OIDC_CLIENT_ID=${MCPHUB_OIDC_CLIENT_ID}
      - OIDC_CLIENT_SECRET=${MCPHUB_OIDC_CLIENT_SECRET}
    volumes:
      - ${CONTAINER_DATA}/mcphub:/app/data
    networks:
      - frontend
      - backend
