services:
  mcphub-postgres:
    labels:
      net.unraid.docker.icon: https://raw.githubusercontent.com/selfhst/icons/main/svg/postgresql.svg
  mcphub:
    labels:
      net.unraid.docker.icon: https://raw.githubusercontent.com/selfhst/icons/main/png/mcphub.png
  mcphub-searxng:
    labels:
      net.unraid.docker.icon: https://raw.githubusercontent.com/selfhst/icons/main/svg/searxng.svg
