services:
  ollama:
    container_name: ollama
    image: ollama/ollama:${OLLAMA_VERSION:-latest}
    restart: ${OLLAMA_RESTART:-unless-stopped}
    environment:
      TZ: ${TZ:-America/Chicago}
      OLLAMA_ORIGINS: ${OLLAMA_ORIGINS:-*}
      OLLAMA_FLASH_ATTENTION: ${OLLAMA_FLASH_ATTENTION:-true}
      OLLAMA_KV_CACHE_TYPE: ${OLLAMA_KV_CACHE_TYPE:-q8_0}
      OLLAMA_CONTEXT_LENGTH: ${OLLAMA_CONTEXT_LENGTH:-48000}
      OLLAMA_HOST: ${OLLAMA_HOST:-0.0.0.0}
      OLLAMA_KEEP_ALIVE: ${OLLAMA_KEEP_ALIVE:-0}
    ports:
      - "${OLLAMA_PORT:-11434}:11434"
    volumes:
      - ${CONTAINER_DATA}/ollama:/root/.ollama:rw"
    mem_limit: ${OLLAMA_MEMORY:-100g}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
